name: tweet_article_links

on: 
  schedule:
    - cron: '0 12,16 * * 1-6'

jobs:
  article_link_post:
    runs-on: macOS-latest
    env:
      access_secret: ${{ secrets.ACCESS_SECRET }}
      access_tok: ${{ secrets.ACCESS_TOK }}
      api_key: ${{ secrets.API_KEY }}
      api_secret: ${{ secrets.API_SECRET }}
      bearer: ${{ secrets.BEARER }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
      
      - name: Install required packages
        run: Rscript -e 'install.packages(c("rtweet", "tidyverse"), dependencies = TRUE)'
      
      #- name: Cache R packages
      #  uses: actions/cache@v1
      
      - name: Create and post tweet
        run: Rscript code/tweet_article_links.R
