name: tweet_digest_link

on: [push]

jobs:
  digest_link_post:
    runs-on: debian-latest
    env:
      access_secret: ${{ secrets.ACCESS_SECRET }}
      access_tok: ${{ secrets.ACCESS_TOK }}
      api_key: ${{ secrets.API_KEY }}
      api_secret: ${{ secrets.API_SECRET }}
      bearer: ${{ secrets.BEARER }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages(c("rtweet", "tidyverse", "httpuv"), dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript code/tweet_digest_link.R
