name: tweet_digest_link

on: [push]

jobs:
  digest_link_post:
    runs-on: ubuntu-latest
    env:
      access_secret: ${{ secrets.ACCESS_SECRET }}
      access_tok: ${{ secrets.ACCESS_TOK }}
      api_key: ${{ secrets.API_KEY }}
      api_secret: ${{ secrets.API_SECRET }}
      bearer: ${{ secrets.BEARER }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
      
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
        
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        
      - name: Create and post tweet
        run: Rscript code/tweet_digest_link.R
